.TH MathLib 3MOD "local:Borchert"
.SH NAME
MathLib, arctan, exp, ln, sin, cos, sqrt \- mathematical library
.SH SYNOPSIS
.DS
PROCEDURE arctan(x: REAL) : REAL;

PROCEDURE exp(x: REAL) : REAL;

PROCEDURE ln(x: REAL) : REAL;

PROCEDURE sin(x: REAL) : REAL;

PROCEDURE cos(x: REAL) : REAL;

PROCEDURE sqrt(x: REAL) : REAL;
.DE
.SH DESCRIPTION
.I Arctan
returns the arc tangent of
.I x
in the range -pi/2 to pi/2.
.PP
.I Exp
returns the exponential function of
.IR x .
.PP
.I Ln
returns the natural logarithm of
.IR x .
.PP
.I Sin
and
.I cos
return trigonometric functions of radian arguments.
.PP
.I Sqrt
returns the square root of
.IR x .
