.TH M2C 1 "local:Borchert"
.SH NAME
m2c \- Modula-2 compiler
.SH SYNOPSIS
.B m2c
[ option ] ... file ...
.SH DESCRIPTION
.I M2c
is the XELOS system Modula-2 compiler.
It accepts several types of arguments:
.PP
Arguments whose names end with `.m2' are taken to be
Modula-2 source programs; they are compiled, and
each object program is left on the file
whose name is that of the source with `.o' substituted
for `.m2'.
Further a reference file with suffix `.r' is left. See
.IR mdb(1)
for more information.
Names ending with `.d' are taken to be Modula-2 definition modules
and compiled, producing a `.sy' file.
The `.o' file is normally deleted, however, if a single
Modula-2 program is compiled and loaded all at one go.
Symbol files and reference files may be archived in
the files `SYM' and `REF'. If these archives exist
.I m2c
tries to archive the corresponding output files.
.PP
In the same way,
arguments whose names end with `.s' are taken to be assembly source programs
and are assembled, producing a `.o' file.
.PP
The following options are interpreted by
.IR m2c .
See
.IR ld (1)
for load-time options.
.TP 8
.B \-c
Suppress the loading phase of the compilation, and force
an object file to be produced even if only one program is compiled.
.TP
.SM
.B \-S
Compile the named Modula-2 programs, and leave the
assembler-language output on corresponding files suffixed `.s'.
.TP
.SM
.BI \-o " output"
Name the final output file
.IR output .
If this option is used the file `a.out' will be left undisturbed.
.TP
.SM
.B \-L
Arrange the compiler to produce a listing for each source file
in a corresponding `.l' file,
or in a `.ld' file if the source is a definition module.
.TP
.SM
.B \-LP
Print a complete listing for all source files on
.I stdout.
.TP
.SM
.BI \-Tdir
Allocate the temporary files of the compiler in the directory
.IR dir .
.TP
.SM
.B \-a
Suppress archiving of the reference and symbol files even if
`SYM' and `REF' exist.
.TP
.SM
.B \-rN
This compiler supports three versions of Modula-2:
unrevised Modula-2 as defined in 1st and 2nd edition of
Wirth's \fIProgramming in Modula-2\fP (\fIN\fP = 0),
revised Modula-2 as defined in the \fIRevisions and Amendments to Modula-2\fP
(\fIN\fP = 1),
and revised Modula-2 as defined in the 3rd edition (default: \fIN\fP = 2).
All compile versions are full compatible.
.TP
.SM
.B \-m
The following argument is taken to be the main module.
Necessary only if no main module exists.
.TP
.SM
.B \-M
Generate stack overflow checks.
This is useful for coroutines only and may only specified
together with \fB-0c\fP.
.TP
.SM
.B \-C
Suppress range checks.
.TP
.SM
.B \-N
Do not put line number information in the object file.
.TP
.SM
.B \-p
Arrange for the compiler to produce code that counts the
number of times each routine is called;
also, if link editing takes place,
replace the standard startoff routine by one that automatically
calls \fIMonitor\fP(3MOD) at the start and arranges to write out
a \fBmon.out\fP file at normal termination of execution of the
object program.
An execution profile can then be generated by use of \fImprof\fP(1).
.TP
.SM
.B \-0c
This option must be present at link time
if coroutines or priorities are used
and causes another startoff routine to be taken.
.TP
.SM
.B \-R
Suppress clean up of temporary files.
.TP
.SM
.B \-v
Verbose flag.
.I M2c
prints all executed commands to standard error.
.TP
.SM
.BI \-7
This option implies
.BI \-S
and causes the compiler to produce assembly code for UNIX Edition VII.
.TP
.SM
.BI \-B \*Sstring
Find substitute compiler passes in the directory named
.I /usr/lib/modula/string
with the files m0, m1, m2, m3, msym.
.br
.mc
.PP
Other arguments
are taken
to be either loader option arguments, or Modula-2 compatible
object programs, typically produced by an earlier
.I m2c
run,
or perhaps libraries of Modula-2 compatible routines.
These programs, together with the results of any
compilations specified, are loaded (in the order
given) to produce an executable program with name
.B a.out.
.SH ENVIRONMENT
.I M2c
looks for two environment parameters:
.B MODLIB
and
.B MODPATH.
If
.B MODLIB
is given
.I m2c
calls the compiler passes in the directory
.B $MODLIB.
.B MODPATH
specifies a list of directories, separated with colons (like
.B PATH).
Each of these directories consists of a
.I SYM
archive of symbol files, a
.I REF
archive of reference files and archives with suffix `.a'.
Archives with leading `p' are intended to be profiled
and are taken if and only if the -p option is present.
In this case other archives are to be ignored.
If the compiler looks for a symbol file or ld(1) for
library modules this search path is used.
.SH FILES
.ta \w'/u/lib/modula/m2_error  'u
file.m2	main or implementation module
.br
file.d	definition module
.br
SYM	archive with symbol files
.br
REF	archive with reference files
file.o	object file
.br
file.sy	symbol file
.br
file.r	reference file
.br
a.out	loaded output
.br
/tmp/mtm*	temporaries for
.I m2c
.br
/u/lib/modula/m[0-3s]*	compiler for
.I m2c
.br
/u/lib/modula/m2e	lister
.br
/u/lib/modula/m2_error	file with error messages
.br
/u/lib/modula/m2rt0.o	runtime startoff
.br
/u/lib/modula/cm2rt0.o	runtime startoff (-0c flag)
.br
/u/lib/modula/mm2rt0.o	runtime startoff (-p flag)
.br
/u/lib/modula/libm2.a	standard library
.br
/u/lib/modula/plibm2.a	profiled standard library
.br
/u/lib/modula/SYM	symbol files of the std library
.br
/u/lib/modula/REF	reference files of the std library
.br
.SH "SEE ALSO"
Niklaus Wirth,
.I Programming in Modula-2,
Springer-Verlag,
1982 (1st ed.) and 1985 (3rd ed.)
.br
Niklaus Wirth,
.I Revisions and Amendments to Modula-2,
ETH Zuerich,
1984
.br
ld(1), mdb(1), mmm(1), mprof(1)
.SH DIAGNOSTICS
The diagnostics produced by Modula-2 itself are intended to be
self-explanatory.
Occasional messages may be produced by the assembler
or loader.
.SH CAVEAT
The first 11 characters of the module name should be identical to the
file name.
